apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scec-nginx.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ include "scec-nginx.name" . }}
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: {{ include "scec-nginx.name" . }}
        tier: frontend
        track: stable
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: {{ include "scec-nginx.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: SSLTYPE
              value: {{ get .Values.ingress.enum .Values.ingress.type | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
