---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "scec-nginx.name" . }}
spec:
  selector:
    app: {{ include "scec-nginx.name" . }}
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      {{ if .Values.ingress.nodePort }}
      nodePort: {{ .Values.ingress.nodePort }}
      {{ end }}
      protocol: TCP
      name: http
  type: NodePort
